version: '3.8' 
services: 
  app:
    image: mike
    build: .
    depends_on:
      - dev-db
    ports:
      - "3009:2000"
    env_file:
      - .env
    networks:
      - test-network
  dev-db:
    image: postgres:15
    environment:
      POSTGRES_DB: cash_adv_n_rtr
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test-network
    ports:
      - 4000:5432
networks:
  test-network:
      driver: bridge
