version: '3.8' 
services: 
  test-db:
    image: postgres:15
    ports:
      - 5434:5434
    environment:
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test-network
  dev-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cash_adv_n_rtr
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - test-network
networks:
  test-network:
    driver: bridge